### ISSUE TITLE
VSCode Insiders integration

### ISSUE THREAD

**Issue by nahuelhds** [sandhje/vscode-phpmd#27]
I've started using insiders because of the multi-folder projects (workspace). In traditional VSCode I'd set and simple `.vscode/settings.json` with the following:

```json
{
  "phpmd.rules": "my/ruleset.xml",
}
```

The thing is that as now I'm working on multiple folders, and every one have its own .vscode/settings.json my rulesets are not being read.

It'd be nice that every project folder read it's own .vscode/settings.json in order to check the PHPMD rules. Right now, under this config that custom rulesets are not being loaded at all.

Thanks in advance

**Comment by nahuelhds** [comment]
What I've done temporarilly is to point to a global ruleset in the general settings. That way the ruleset I need are being check the way I need. Anyway, I rather use particular ruleset.xml per project. But just for all people know if they have the same issue

**Comment by sandhje** [comment]
Thank you Nahuel for your feedback and feature request. This would indeed be a big improvement. Once I get some spare time and start working on the next version of the extension I will look into this.

**Comment by sandhje** [comment]
This can be achieved with ${workspaceFolder} sinc PR #51
