### ISSUE TITLE
problems to be marked as error

### ISSUE THREAD

**Issue by JohnstonCode** [sandhje/vscode-phpmd#29]
Can any issues listed by phpmd be listed as errors rather than info in the problems list?

**Comment by sandhje** [comment]
The extension maps the "priority" of the reported phpmd problems to vscode "severity". By creating a PHPMD ruleset file and setting that in the extension's configuration you can control how the problems are "shown" within vscode. See https://phpmd.org/documentation/creating-a-ruleset.html on how to create a ruleset file and how to set priority for specific rules.

The mapping within the extension is as follows:

| PHPMD Priority | VSCode severity |
| ------------------|-------------------|
| 1 | DiagnosticSeverity.Error |
| 2 | DiagnosticSeverity.Warning |
| 3 | DiagnosticSeverity.Information |
| 4 | DiagnosticSeverity.Hint | 
| 5 | DiagnosticSeverity.Hint |
