### ISSUE TITLE
Clear problems on file close

### ISSUE THREAD

**Issue by jmfederico** [sandhje/vscode-phpmd#36]
Currently, when a file is closed, this extensions does not clear the problems it generated, polluting the "problems" view in VSCode.

On big projects one ends up with a massive amount of errors which might belong to files that can't be fixed (files for other libraries, for instance).

It would be great if the Problems were cleared when closing the file.

**Comment by sandhje** [comment]
Hi,

Thank you for reporting, I will look into this issue.

**Comment by eddiebeltran33** [comment]
I have the same problem. Is there anything I can provide to help?

**Comment by sandhje** [comment]
Hi,

Any help with maintaining this extension is appreciated, you're more than welcome to fork the repo and submit a PR for any functionality you wish to see added to the extension, or any bug fixed. If you need help setting up a dev environment feel free to contact me, e.g. through gitter. Another way to help would be to make days last more than 24 hours for me or put more than 7 days in a week for me, but I guess that's a little bit harder than the fork-PR thing ;). 

Anyway, regarding this issue I just created a fix which is working on my dev machine now. I'll ship a new version somewhere in the coming days. Just need to create some unit tests and add a config value so the new behaviour can be disabled if needed.

**Comment by sandhje** [comment]
Resolved in PR #39.  Fix will be in next release.

**Comment by jmfederico** [comment]
Thank you for this fix!
