### ISSUE TITLE
Unable to execute PHPMD command (phpmd) - works fine on local file with Windows, but not with WinSCP

### ISSUE THREAD

**Issue by giorgio79** [sandhje/vscode-phpmd#41]
Hello,

I am using VS Code with phpmd, and the tool works fine on local php files. ( I installed php and compose in C:/bin, and added it to user vars. Wherever I type phpmd in command line the tool works.

I set the 

When I open a file with WinSCP I get this error message though:
Unable to execute PHPMD command (phpmd)

Any tips?
in VsCode:
![image](https://user-images.githubusercontent.com/283347/45267812-f9ccfe00-b473-11e8-8c72-5b8d6fac011d.png)

in cmd
![image](https://user-images.githubusercontent.com/283347/45267818-0baea100-b474-11e8-9a97-4d5ea129bc3f.png)

**Comment by sandhje** [comment]
Could you please attach the verbose logging from the output panel, maybe I can help you then.

**Comment by sandhje** [comment]
Closing since there has been no response on the request for the verbose logging output
