### ISSUE TITLE
Add support of anonymous classes

### ISSUE THREAD

**Issue by Danila1985** [sandhje/vscode-phpmd#43]
I have false-positive message `
      Avoid unused local variables such as '$prop'.
    ` in anonymous class placed inside another class or function:

function getData($var)
{
    return new class($var)
    {
        private $prop;

        public function __construct($var)
        {
            $this->prop = $var;
        }

        public function getProp()
        {
            return $this->prop;
        }
    };
}

**Comment by sandhje** [comment]
Sorry for the late response! I'm afraid this is something you should take up with the PHPMD team (https://phpmd.org/). There is also a way to surpress certain warnings or create your own PHPMD rules, see https://phpmd.org/documentation/index.html.
