### ISSUE TITLE
VSCode:Problems Panel Output

### ISSUE THREAD

**Issue by tlorens** [sandhje/vscode-phpmd#48]
It appears that PHP Mess Detector output doesn't trim the messages.  The type of problem icon shows and then a CR/LF.  It doesn't look like the other messages that appear from other linters.  

![Screen Shot 2019-07-10 at 11 46 23 AM](https://user-images.githubusercontent.com/135409/60983675-602ae300-a308-11e9-8738-0afbbef2b68d.png)

**Comment by mwsv** [comment]
It's especially annoying thing when you use phpmd plugin together with:

[https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens](url)

**Comment by sandhje** [comment]
Will be fixed with the next version
