### ISSUE TITLE
PHP XML extension needed to work

### ISSUE THREAD

**Issue by beto-aveiga** [sandhje/vscode-phpmd#52]
I was having issues with running PHP mess detector on save because `simplexml_load_string` function was not found. In my particular case I had to install XML library with `sudo apt install php7.2-xml -y` and restart `Apache` to make it work. I think this should be present in the documentation. 
Thanks!

**Comment by sandhje** [comment]
This is indeed a PHPMD requirement. Added a requirements section to the readme ([commit](https://github.com/sandhje/vscode-phpmd/commit/392f09b2356d7477e0914cbad9b6ceb00d5e3e20)), with the next release of the extension this will be updated.
