### ISSUE TITLE
Error to found file when using jira extension for pull request

### ISSUE THREAD

**Issue by eduardohenriquesousasilva** [sandhje/vscode-phpmd#55]
Hi, so when I opend my code with the extension for Jira to do pull requests, the extension crash because it  doesn't identify the real path of file.. 

Can you help me?

Error message:
An error occured during document validation after open with the following message: ENOENT: no such file or directory, open '/Feature/
![image](https://user-images.githubusercontent.com/29388404/82455967-fd5aba00-9a89-11ea-9610-1f506072bab2.png)

**Comment by sandhje** [comment]
It appears the Jira extension opens the file "virtually". Meaning the file isn't really at that location but served directly from the server. This is not a supported scenario for the phpmd extension. 

If you want you can prevent the extension from trying to run for the "/Feature" path by setting the phpmd command in settings manually and using the "--exclude" option. See https://phpmd.org/documentation/index.html for more info.

**Comment by eduardohenriquesousasilva** [comment]
> It appears the Jira extension opens the file "virtually". Meaning the file isn't really at that location but served directly from the server. This is not a supported scenario for the phpmd extension.
> 
> If you want you can prevent the extension from trying to run for the "/Feature" path by setting the phpmd command in settings manually and using the "--exclude" option. See https://phpmd.org/documentation/index.html for more info.

It's a good idea, thanks @sandhje and I would like to say that vscode extension is good thanks
