### ISSUE TITLE
False error 'unused private fields'

### ISSUE THREAD

**Issue by soanarin** [sandhje/vscode-phpmd#65]
I have a class where I declare a private property which then is used multiple times in the class, but the error shows 'avoid unused private fields'. Thank you for looking into this.
![Screenshot from 2021-12-01 08-00-26](https://user-images.githubusercontent.com/27398906/144180325-2717f038-d185-4812-8c6d-c970f0db29f3.png)

**Comment by sandhje** [comment]
Sorry I can't fix this, the extension only shows the warnings generated by PHPMD as vscode diagnostics (the curly underline). 

If a PHPMD rule does not work correctly you should take this up with the authors of PHPMD (https://phpmd.org/). If you set the extension to "verbose logging" in the settings, the PHPMD command will be logged in the output panel. This command can be executed in any cli to generate the "raw" PHPMD output which is probably what you need to report an error with the PHPMD maintainers.
